name: CI

on:
  push:
    branches: [ main, master, test ]
  pull_request:
    branches: [ main, master, test ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest -q